package com.marcos.bitcoin.models

import org.json.JSONObject

/**
 * Wallet information data model
 * Used to receive wallet information generated by JS
 */
data class BitcoinWallet(
    val network: String,
    val mnemonicLength: Int?,
    val mnemonic: String?,
    val privateKey: String,
    val publicKey: String,
    val addresses: BitcoinAddresses
) {
    companion object {
        /**
         * Initialize from JSONObject (for parsing JS returned data)
         */
        fun fromJson(json: JSONObject): BitcoinWallet? {
            return try {
                val addressesJson = json.getJSONObject("addresses")
                val addresses = BitcoinAddresses.fromJson(addressesJson) ?: return null
                
                BitcoinWallet(
                    network = json.getString("network"),
                    mnemonicLength = if (json.has("mnemonicLength") && !json.isNull("mnemonicLength")) {
                        json.getInt("mnemonicLength")
                    } else null,
                    mnemonic = if (json.has("mnemonic") && !json.isNull("mnemonic")) {
                        json.getString("mnemonic")
                    } else null,
                    privateKey = json.getString("privateKey"),
                    publicKey = json.getString("publicKey"),
                    addresses = addresses
                )
            } catch (e: Exception) {
                null
            }
        }
    }
    
    /**
     * Get preferred address (prioritize segwit, then legacy, finally taproot)
     */
    val preferredAddress: String
        get() = when {
            addresses.segwit.isNotEmpty() -> addresses.segwit
            addresses.legacy.isNotEmpty() -> addresses.legacy
            else -> addresses.taproot
        }
    
    /**
     * Convert to JSONObject
     */
    fun toJson(): JSONObject {
        return JSONObject().apply {
            put("network", network)
            mnemonicLength?.let { put("mnemonicLength", it) }
            mnemonic?.let { put("mnemonic", it) }
            put("privateKey", privateKey)
            put("publicKey", publicKey)
            put("addresses", addresses.toJson())
        }
    }
}
